# Generated by Django 6.0 on 2025-12-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='User', max_length=100),
        ),
    ]
